# Generated by Django 3.2 on 2022-10-09 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20221007_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured_image_url',
        ),
    ]
