# Generated by Django 3.2 on 2022-10-06 17:55

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stylist_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('stylist_email', models.EmailField(max_length=254)),
                ('stylist_phone', models.CharField(max_length=11)),
                ('brand_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('specialty', models.CharField(choices=[('Braids', 'Braids'), ('Wigs', 'Wigs'), ('Weaves', 'Weaves'), ('Locs', 'Locs'), ("Men's Hair", "Men's Hair"), ('Natural Hair', 'Natural Hair'), ("Kid's Hair", "Kid's Hair")], default=0, max_length=15)),
                ('hairstyles', models.TextField()),
                ('price_from', models.DecimalField(decimal_places=2, max_digits=3)),
                ('requirements', models.TextField()),
                ('mobile', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('street_address1', models.CharField(max_length=80)),
                ('street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('town_or_city', models.CharField(max_length=40)),
                ('county', models.CharField(blank=True, max_length=80, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stylist_brand', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='stylist_like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['price_from'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('review_title', models.TextField(max_length=30)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='stylists.stylist')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
