# Generated by Django 3.2 on 2022-10-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylists', '0002_alter_stylist_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylist',
            name='price_from',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
