# Generated by Django 3.2 on 2022-10-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylists', '0003_alter_stylist_price_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='brand_image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
