# Generated by Django 3.2 on 2022-10-07 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stylists', '0004_stylist_brand_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stylist',
            options={'ordering': ['price']},
        ),
        migrations.RenameField(
            model_name='stylist',
            old_name='brand_name',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='stylist',
            old_name='price_from',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='stylist',
            old_name='stylist_name',
            new_name='stylist',
        ),
    ]
