# Generated by Django 3.2 on 2022-10-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylists', '0005_auto_20221007_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='website',
            field=models.URLField(default=''),
        ),
    ]
