# Generated by Django 3.2 on 2022-10-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylists', '0006_stylist_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='live',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
    ]
